### PR TITLE
Ensure `sd_journal_get_fd` is called directly after `sd_journal_open`

### PR DESCRIPTION
**Pull request by errm**
This ensures that inotify properly tracks journal rotation fixing #70
and should also guard against the issues in https://github.com/systemd/systemd/issues/7998 and https://github.com/rsyslog/rsyslog/pull/2437

### CODE REVIEW

**Comment by ledbettj** [comment]
Thanks!

I see that Travis is being a nightmare.  When I set it up, Ubuntu did not ship systemd so I had to build it manually;  I have to believe that Travis has updated their Ubuntu version offering enough that it should be included (right?).

I guess what I'm saying is that I'm not terribly worried about Travis so if you want to just add the call to `file_descriptor` we can push a release with that and deal with Travis later/separately :)

**Comment by errm** [comment]
Sadly the latest Ubuntu on travis is still 14.04 - its only 4 years old 😱 
On fluent-plugin-systemd I ended up using a docker image for this stuff ... this also has the advantage that it can be more easily tried out localy ....

**Comment by errm** [comment]
Ok this should be good enough for now ...

I allowed the build against the latest ubuntu version to fail for now, but I will come back and fix it later ...

**Comment by ledbettj** [comment]
Thanks for managing to get Travis working!

**Comment by ledbettj** [comment]
I tagged and pushed this as v1.3.2

**Pull request merged**
